/**
 * Media entry sanitizer.
 *
 * Validates and cleans media entries against the core schema defined in
 * `server/resource/media-data-schema.json`. Workflow-specific extra inputs
 * are nested under `extraInputs`; unrecognized top-level fields are stripped.
 *
 * @module features/media/sanitizer
 */
import fs from 'fs';
import path from 'path';
import { RESOURCE_DIR } from '../../core/paths.mjs';

const SCHEMA_PATH = path.join(RESOURCE_DIR, 'media-data-schema.json');
const WORKFLOWS_PATH = path.join(RESOURCE_DIR, 'comfyui-workflows.json');

// Cache loaded files to avoid repeated disk reads per request
let _schema = null;
let _workflowsData = null;

function getSchema() {
  if (!_schema) {
    _schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
  }
  return _schema;
}

function getWorkflowsData() {
  if (!_workflowsData) {
    _workflowsData = JSON.parse(fs.readFileSync(WORKFLOWS_PATH, 'utf8'));
  }
  return _workflowsData;
}

/**
 * Find a workflow config by name.
 * @param {string} workflowName
 * @returns {Object|null} The workflow object or null if not found.
 */
export function loadWorkflowConfig(workflowName) {
  if (!workflowName) return null;
  try {
    const data = getWorkflowsData();
    const wf = (data.workflows || []).find(w => w.name === workflowName);
    return wf || null;
  } catch (err) {
    console.error('sanitizer: failed to load workflow configs:', err);
    return null;
  }
}

/**
 * Build the set of valid extra-input IDs for a workflow config.
 * Includes declared `extraInputs` IDs plus `image_N_uid` / `audio_N_uid` keys.
 * @param {Object} workflowConfig
 * @returns {Set<string>}
 */
function buildValidExtraInputIds(workflowConfig) {
  const ids = new Set();
  const opts = workflowConfig.options || {};

  if (Array.isArray(opts.extraInputs)) {
    opts.extraInputs.forEach(input => ids.add(input.id));
  }

  const inputImages = opts.inputImages || 0;
  for (let i = 0; i < inputImages; i++) {
    ids.add(`image_${i}_uid`);
  }

  const inputAudios = opts.inputAudios || 0;
  for (let i = 0; i < inputAudios; i++) {
    ids.add(`audio_${i}_uid`);
  }

  return ids;
}

/**
 * Sanitize a media entry against the core schema and optional workflow config.
 *
 * - Non-core top-level fields are moved into `entry.extraInputs`.
 * - If `workflowConfig` is provided, `extraInputs` is filtered to only known IDs
 *   and missing extra inputs are filled with their workflow defaults.
 * - If `workflowConfig` is null, all non-core fields are kept in `extraInputs`
 *   as a best-effort catch-all (unknown / deleted workflow).
 * - Missing core fields are filled with their schema defaults.
 * - Auto-generated fields (`uid`, `timestamp`, `folder`) are preserved as-is.
 *
 * @param {Object} entry - The raw media entry.
 * @param {Object|null} workflowConfig - The workflow configuration or null.
 * @returns {Object} The sanitized entry (same reference, mutated in place).
 */
export function sanitizeMediaEntry(entry, workflowConfig) {
  const schema = getSchema();
  const coreFields = new Set(Object.keys(schema.fields));

  // --- Collect existing extraInputs ---
  const existingExtras = (entry.extraInputs && typeof entry.extraInputs === 'object' && !Array.isArray(entry.extraInputs))
    ? { ...entry.extraInputs }
    : {};

  // --- Move unrecognized top-level fields into extraInputs ---
  const cleanedEntry = {};
  for (const [key, value] of Object.entries(entry)) {
    if (key === 'extraInputs') continue; // handled separately
    if (coreFields.has(key)) {
      cleanedEntry[key] = value;
    } else {
      existingExtras[key] = value;
    }
  }

  // --- Fill missing core fields with schema defaults ---
  for (const [field, def] of Object.entries(schema.fields)) {
    if (def.autoGenerated) continue; // leave auto-generated fields to the database layer
    if (cleanedEntry[field] === undefined) {
      cleanedEntry[field] = def.default !== undefined ? def.default : null;
    }
  }

  // --- Filter / fill extraInputs based on workflow config ---
  let finalExtras;
  if (workflowConfig) {
    const validIds = buildValidExtraInputIds(workflowConfig);
    finalExtras = {};

    // Keep only recognized extra inputs
    for (const [key, value] of Object.entries(existingExtras)) {
      if (validIds.has(key)) {
        finalExtras[key] = value;
      }
    }

    // Fill missing extra input defaults from the workflow config
    const opts = workflowConfig.options || {};
    if (Array.isArray(opts.extraInputs)) {
      opts.extraInputs.forEach(input => {
        if (finalExtras[input.id] === undefined && input.default !== undefined) {
          finalExtras[input.id] = input.default;
        }
      });
    }
  } else {
    // Unknown workflow: keep everything in extraInputs without filtering
    finalExtras = existingExtras;
  }

  cleanedEntry.extraInputs = finalExtras;

  // Replace all keys in the original entry object
  for (const key of Object.keys(entry)) {
    delete entry[key];
  }
  Object.assign(entry, cleanedEntry);

  return entry;
}
